:stem: latexmath

== Layered Standard Manifest File [[layered-standard-manifest-file]]

This layered standard requires the use of a layered standard manifest file and it shall be stored inside the FMU at the following path: `/extra/org.fmi-standard.fmi-ls-dae/fmi-ls-manifest.xml`.

Several new elements are included as direct children of the root element in the layered standard manifest file to describe the DAE formulation.

.`fmiDAEManifest` child elements.
[[table-schema-fmiDAEManifest]]
[cols="1,3",options="header"]
|====
|Element
|Description

|<<EnableDAEParameter>>
|Required element referencing the https://fmi-standard.org/docs/3.0.2/#structuralParameter[structural parameter] in `modelDescription.xml` that enables DAE mode.

|<<AlgebraicVariables>>
|List of all <<AlgebraicVariables, algebraic variables>> exposed for the DAE formulation.

|<<ModelStructure>>
|Defines the structure of the DAE formulation for the model.
Especially, the ordered lists of https://fmi-standard.org/docs/3.0.2/#output[outputs], continuous-time https://fmi-standard.org/docs/3.0.2/#state[states], and the initial unknowns (the unknowns during *https://fmi-standard.org/docs/3.0.2/#InitializationMode[InitializationMode]*) are *re*-defined and overwrite the corresponding https://fmi-standard.org/docs/3.0.2/#ModelStructure[ModelStructure] present in the `modelDescription.xml`, with the addition of the  <<Residual, residuals>> element.
The <<AlgebraicVariables,algebraic variables>> can be included as dependencies, and can also be initial unknowns.

|<<Annotations>>
|Optional annotations for the top-level element.

|====

The XML attributes of `<fmiDAEManifest>` are:

.`<fmiDAEManifest>` attribute details.
[[table-schema-fmiDAEManifest-attributes]]
[cols="1,1,1,2",options="header"]
|====
|Attribute
|Namespace
|Value
|Description

|`fmi-ls-name`
|`http://fmi-standard.org/fmi-ls-manifest`
|`org.fmi-standard.fmi-ls-dae`
|Name of the layered standard in reverse domain name notation.

|`fmi-ls-version`
|`http://fmi-standard.org/fmi-ls-manifest`
|`1.0.0-alpha.1`
|Version of the layered standard. This layered standard uses semantic versioning, as defined in <<PW13>>.

|`fmi-ls-description`
|`http://fmi-standard.org/fmi-ls-manifest`
|`Layered standard for DAE support in FMI.`
|String with a brief description of the layered standard that is suitable for display to users.
|====

=== Enabling DAE mode [[EnableDAEParameter, `<EnableDAEParameter>`]]

The element <<EnableDAEParameter>> references the https://fmi-standard.org/docs/3.0.2/#structuralParameter[structural parameter] in the `modelDescription.xml` that enables DAE mode.
See <<enable-dae-mode-variable>> for the full semantics and the calling sequences used to change the mode.

.Attributes to <<EnableDAEParameter>> element.
[[table-enable-dae-details]]
[cols="1,5a", options="header"]
|====
|Attribute
|Description

|`valueReference`
|[[enableDAEModeVariable, `valueReference`]]
The https://fmi-standard.org/docs/3.0.2/#table-variableBase-attributes[value reference] of the structural parameter present in the `ModelVariables` of the `modelDescription.xml` that enables DAE mode.
|====

=== Algebraic variables [[AlgebraicVariables, `<AlgebraicVariables>`]]

The element <<AlgebraicVariables>> defines the list of the algebraic variables.

.AlgebraicVariables elements.
[[table-algebraic-variables-details]]
[cols="1,5a", options="header"]
|====
|Element
|Description

|`AlgebraicVariable`
|An <<AlgebraicVariable>> present in the `ModelVariables` element of the modelDescription.xml.
|====

[[AlgebraicVariable, `<AlgebraicVariable>`]]
Each <<AlgebraicVariable>> has only one attribute defining the value reference.

.Attributes to <<AlgebraicVariable>> element.
[[table-alg-details]]
[cols="1,5a", options="header"]
|====
|Attribute
|Description

|`valueReference`
|The value reference for the algebraic variable present in the `ModelVariables` of the modelDescription.xml.
|====

NOTE: In the core Model Exchange standard there exists the API function *https://fmi-standard.org/docs/3.0.2/#fmi3GetNominalsOfContinuousStates[fmi3GetNominalsOfContinuousStates]*, which only holds for the continous time states. There is currently no extension of the API for fmi-ls-dae. The algebraic variable could still have a nominal value defined by the `nominal` attribute for variables under `ModelVariables` of the `modelDescription.xml`, but in this case the nominal is constant.

=== Model Structure [[ModelStructure,`<ModelStructure>`]]

The structure of the model for the DAE-formulation is defined in element <<ModelStructure>>.
It defines the <<model-dependencies,dependencies>> between variables.
The <<ModelStructure>> element is extended with an additional element - <<Residual>> - and the optional dependencies can now include algebraic variables.

An FMU that follows this layered standard must expose all residuals using the <<Residual>> element.

The <<ModelStructure>> defined here extends the one from the core FMI standard.
All elements defined in the core standard (`Output`, `ContinuousStateDerivative`, `ClockedState`, `InitialUnknown`, `EventIndicator`) retain their existing semantics in this manifest, with the additions that:

* Each element's `dependencies` attribute may now also reference <<AlgebraicVariable, algebraic variables>>.
* The `InitialUnknown` element may reference an algebraic variable.

The <<ModelStructure>> element is extended with one additional element, <<Residual>>, described below.

.Additional ModelStructure element.
[#table-model-structure-dae-element]
[cols="1,5a",options="header"]
|====
|Element
|Description

|`Residual`
|[[Residual,`<Residual>`]]
Ordered list of residual equations (constraints). Each residual element must reference a unique variable present in the `ModelVariables` of the `modelDescription.xml`. It is the importer's responsiblity to find the values of the <<AlgebraicVariables, algebraic variables>> such that the residuals are 0.
The functional dependency is defined as: +
latexmath:[{0 := \mathbf{f}_{\mathit{res}}(\mathbf{x}_c, \mathbf{a}_c, \mathbf{u}_c, t, \mathbf{p})}]
|====

.Attributes to `<<Residual>>` element.
[[table-residual-details]]
[cols="1,5a", options="header"]
|====
|Attribute
|Description

|`valueReference`
|The value reference of the residual variable latexmath:[{v_{\mathit{unknown}}}], which must be present in the `ModelVariables` element of the `modelDescription.xml`.

|`dependencies`
|[[model-dependencies]]
Optional attribute defining the algebraic dependencies as a list of value references of the knowns latexmath:[{\mathbf{v}_{\mathit{known}}}] that this residual equation directly depends on.

Knowns latexmath:[{\mathbf{v}_{\mathit{known}}}] in *https://fmi-standard.org/docs/3.0.2/#ContinuousTimeMode[ContinuousTimeMode]* (ME) for `<<Residual>>` elements are: +

* inputs (variables with https://fmi-standard.org/docs/3.0.2/#causality[causality] = https://fmi-standard.org/docs/3.0.2/#input[input]),

* continuous states,

* continuous state derivatives,

* parameters (variables with https://fmi-standard.org/docs/3.0.2/#causality[causality] = https://fmi-standard.org/docs/3.0.2/#parameter[parameter]),

* algebraic variables (variables listed in an `<<AlgebraicVariables>>` element),

* https://fmi-standard.org/docs/3.0.2/#independent[independent] variable (usually time; https://fmi-standard.org/docs/3.0.2/#causality[causality] = https://fmi-standard.org/docs/3.0.2/#independent[independent]).

If `dependencies` is not present, it must be assumed that the residual depends on all knowns.
If `dependencies` is present as an empty list, the residual depends on none of the knowns.
Otherwise the residual depends on the knowns defined by the given value references.

|`dependenciesKind`
|See the description of https://fmi-standard.org/docs/3.0.2/#dependenciesKind[`dependenciesKind`] in the core FMI standard.

|====

---

=== Getting Partial Derivatives

The partial derivative API functions https://fmi-standard.org/docs/3.0.2/#fmi3GetDirectionalDerivative[fmi3GetDirectionalDerivative] and https://fmi-standard.org/docs/3.0.2/#fmi3GetAdjointDerivative[fmi3GetAdjointDerivative] are used as defined in the core FMI standard, with the following extensions for DAE FMUs:

* <<Residual, Residual>> variables can appear as unknowns.
* <<AlgebraicVariable, Algebraic variables>> could appear as knowns for any unknown.

---

=== Hello World DAE Example

Below outlines how to map the different forms of the Hello World DAE Example to the manifest file detailed here.

==== Hello World DAE - Fully-Implicit DAE

The fully-implicit representation

[latexmath]
++++
F(\dot{x}, x, t) = 0
++++

is given by

[latexmath]
++++
F: \mathbb{R}^3 \times \mathbb{R}^3 \times \mathbb{R} \to \mathbb{R}^3,
\begin{pmatrix}
x \\
\dot{x} \\
t
\end{pmatrix}
\mapsto
\begin{pmatrix}
F_1 \\
F_2 \\
F_3
\end{pmatrix}
=
\begin{pmatrix}
\dot{x_1}   - x_2   \\
x_2 + 2 x_3 - x_1   \\
x_2 - 3 x_3 - 2 x_1
\end{pmatrix}
++++

Assume the FMU has these variables:

[cols="1,1", options="header"]
|====
|Variable | valueReference
|`enableDAEModeVariable` | 0
|latexmath:[t] | 1
|latexmath:[x_1] | 2
|latexmath:[x_2] | 3
|latexmath:[x_3] | 4
|latexmath:[\dot{x_1}] | 5
|latexmath:[\dot{x_2}] | 6
|latexmath:[\dot{x_3}] | 7
|latexmath:[F_1] | 8
|latexmath:[F_2] | 9
|latexmath:[F_3] | 10
|====

In this case `x_2` and `x_3` do not appear differentiated in any equations, hence they are classified as algebraic (contained in an `<<AlgebraicVariable>>` element).
An example of the `<<EnableDAEParameter>>`, `<<AlgebraicVariables>>` and `<<ModelStructure>>` elements would be:

```xml
<EnableDAEParameter
  valueReference="0"/>
<AlgebraicVariables>
  <AlgebraicVariable valueReference="3"/> <!-- x_2 -->
  <AlgebraicVariable valueReference="4"/> <!-- x_3 -->
</AlgebraicVariables>
<ModelStructure>
  <Residual
    valueReference="8"
    dependencies="5 3"
    dependenciesKind="fixed fixed"/> <!-- F1 -->
  <Residual
    valueReference="9"
    dependencies="2 3 4"
    dependenciesKind="fixed fixed fixed"/> <!-- F2 -->
  <Residual
    valueReference="10"
    dependencies="2 3 4"
    dependenciesKind="fixed fixed fixed"/> <!-- F3 -->
</ModelStructure>
```
NOTE: The derivatives of `x_1`, `x_2`, and `x_3` (`\dot{x_1}`, `\dot{x_2}`, `\dot{x_3}`) are still noted with the `derivative` attribute under the `ModelVariables` element in the `modelDescription.xml`, which gives the importer all the information they need to solve the equations.

==== Hello World DAE - Semi-Explicit DAE

The semi-explicit representation

[latexmath]
++++
\begin{split}
\dot{x} & = f(x, y, t) \\
      0 & = g(x, y, t)
\end{split}
++++

is given by

[latexmath]
++++
\begin{split}
f: \mathbb{R} \times \mathbb{R}^2 \times \mathbb{R} \to \mathbb{R}, \;
&(x,y,t) \mapsto
\begin{pmatrix}
y_1
\end{pmatrix}
 \\
g: \mathbb{R} \times \mathbb{R}^2 \times \mathbb{R} \to \mathbb{R}, \;
&(x,y,t) \mapsto
\begin{pmatrix}
y_1 + 2 y_2 - x   \\
y_1 - 3 y_2 - 2 x
\end{pmatrix}
\end{split}
++++

Assume the FMU has the following variables:

[cols="1,1", options="header"]
|====
|Variable | valueReference
|`enableDAEModeVariable` | 0
|latexmath:[t] | 1
|latexmath:[x] | 2
|latexmath:[y_1] | 3
|latexmath:[y_2] | 4
|latexmath:[\dot{x}] | 5
|latexmath:[g_1] | 6
|latexmath:[g_2] | 7
|====

This case contains the same algebraic variables.
However this time the the derivative of `x` is given in explicit form in the `ModelStructure`:

```xml

<EnableDAEParameter
  valueReference="0"/>
<AlgebraicVariables>
  <AlgebraicVariable valueReference="3"/> <!-- y1 -->
  <AlgebraicVariable valueReference="4"/> <!-- y2 -->
</AlgebraicVariables>
<ModelStructure>
  <ContinuousStateDerivative
    valueReference="5"
    dependencies="3"
    dependenciesKind="fixed"/> <!-- dot(x) = y1 -->
  <Residual
    valueReference="6"
    dependencies="2 3 4"
    dependenciesKind="fixed fixed fixed"/> <!-- g1: y1 + 2*y2 - x = 0 -->
  <Residual
    valueReference="7"
    dependencies="2 3 4"
    dependenciesKind="fixed fixed fixed"/> <!-- g2: y1 - 3*y2 - 2*x = 0 -->
</ModelStructure>
```

==== Hello World DAE - Explicit ODE

This simple system could also be transformed into an explicit ODE formulation

[latexmath]
++++
\begin{split}
\dot{x} &= \frac{7}{5}x
\end{split}
++++

with local variables latexmath:[y] and latexmath:[z]

[latexmath]
++++
\begin{split}
y       &= \frac{7}{5}x   \\
z       &= -\frac{x}{5}
\end{split}
++++

and exported as an ODE ModelExchange FMU:

[cols="1,1", options="header"]
|====
|Variable | valueReference
|latexmath:[t] | 1
|latexmath:[x] | 2
|latexmath:[y] | 3
|latexmath:[z] | 4
|latexmath:[\dot{x}] | 5
|====

This would correspond to the regular ODE ModelStructure:

```xml
<ModelStructure>
  <!-- dot(x) = 7/5 * x -->
  <ContinuousStateDerivative
    valueReference="5"
    dependencies="2"
    dependenciesKind="fixed"/>
</ModelStructure>
```
